services:
  app:
    container_name: retrostats-app
    build: ./app
    image: retrostats-app:latest
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - strapi
    depends_on:
      - api
  api:
    container_name: retrostats-api
    build: ./api
    image: retrostats-api:latest
    restart: always
    env_file: .env
    volumes:
      - ./api/prisma:/app/prisma
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/package-lock.json:/app/package-lock.json
      - ./api/tsconfig.build.json:/app/tsconfig.build.json
      - ./api/tsconfig.json:/app/tsconfig.json
      - .env:/app/.env
    ports:
      - "3001:3001"
    networks:
      - strapi
    depends_on:
      - strapi
  strapi:
    container_name: retrostats-cms
    build: ./cms
    image: retrostats-cms:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      # - ./node_modules:/opt/node_modules
      # - ./cms/yarn.lock:/opt/yarn.lock
      - .env:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - database

  database:
    container_name: database-retrostats
    image: mysql:8.2.0
    restart: unless-stopped
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - retrostats-database:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - strapi

volumes:
  retrostats-database:

networks:
  strapi:
    name: strapi
    driver: bridge