# fly.toml app configuration file generated for retrostats-cms on 2025-01-14T12:06:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'retrostats-cms'
primary_region = 'mad'

[build]

[env]
  ADMIN_JWT_SECRET = 'tobemodified'
  API_TOKEN_SALT = 'tobemofidied'
  APP_KEYS = 'tobemodified'
  DATABASE_CLIENT = 'mysql'
  DATABASE_HOST = 'retrostats-database.internal'
  DATABASE_NAME = 'retrostats'
  DATABASE_PASSWORD = 'retrostats'
  DATABASE_PORT = '3306'
  DATABASE_URL = 'mysql://retrostats:retrostats@retrostats-database.internal:3306/retrostats'
  DATABASE_USERNAME = 'retrostats'
  JWT_SECRET = 'tobemodified'
  SECRET = 'tobemofied'
  TRANSFER_TOKEN_SALT = 'tobemofied'

[http_service]
  internal_port = 1337
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
